version: "3.9"

services:
  # Game
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    env_file:
      - ./.env
  minio:
    image: minio/minio:latest
    ports:
      - "9100:9100"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address :9100